### PR TITLE
Improve document 📄 "Action" tab

### PR DESCRIPTION
**Pull request by AshishViradiya153**
Fixes https://github.com/mfts/papermark/issues/677

- The user can create a data room using the "Action" tabs if they have the correct subscription; otherwise, an "Upgrade Plan" tab will be shown.
- Display a tooltip for "Upload a new version." (The problem is that if we wrap the button with a tooltip, the button event doesn't work.)

image
image

### CODE REVIEW

**Comment by AshishViradiya153** [comment]
@mfts could you please review and let me know if there’s anything further needed from my side?

**Comment by mfts** [comment]
@AshishViradiya153 I think we should hide the "add to dataroom" if the user is either on free or pro and not on trial

**Comment by AshishViradiya153** [comment]
"Add to Dataroom" is always there, which I think is great. If the user doesn't have a Dataroom, it will be hidden. Additionally, users can create a new Dataroom using the "Create Dataroom" option if they have the right plan; otherwise, an upgrade popup will appear.

**Comment by AshishViradiya153** [comment]
@mfts Recheck please

**Comment by AshishViradiya153** [comment]
@mfts Please recheck, I have removed the "Create New Dataroom" option and also hidden "datarooms" if there aren't any.

**Review by mfts — APPROVED** [review]

**Comment by mfts** [comment]
@AshishViradiya153 i think something went wrong with the award. could you please open an issue referencing this PR and then I award you there

**Pull request merged**
