### PR TITLE
fix: pass theme option as url params

### LINKED ISSUE #791: [🕹️] Support dark mode in Notion page view
### What side quest or challenge are you solving?

Papermark supports sharing Notion pages. 

Sometimes, Notion pages are default dark mode and the users who shares a Notion page via Papermark wants to keep that color scheme. 

We are using `react-notion-x` to parse and visualize Notion pages. Currently we hard-coded the color-scheme to light mode. 
https://github.com/mfts/papermark/blob/80299d2906ff6421d59292c4f95c7a24f0ab27a8/components/NotionPage.tsx#L315

However, I believe there should be a setting to make this whatever the original Notion page is. 

### Points

150 Points

### Description

_No response_

### Provide proof that you've completed the task

Open a PR with the working code and a short video showing the original notion page and the notion page on Papermark that shows that it persists the color-scheme (light or dark) based on the Notion page's original setting

### PR DESCRIPTION
**Pull request by DeepaPrasanna**
fixes #791 

Summary of changes: passed mode as the url param in the notion link and update the darkMode value in Notion doc

Screenshot 2024-10-17 190309
Screenshot 2024-10-17 190250

### CODE REVIEW

**Comment by mfts** [comment]
@DeepaPrasanna I think we have a misunderstanding. 

The sender should add the `?theme=dark|light` to the Notion URL when they are uploading it to Papermark. 
From there we are extracting it and passing it into the `NotionPage` component.

**Review by mfts — CHANGES_REQUESTED** [review]
@DeepaPrasanna I think we have a misunderstanding. 

The sender should add the `?theme=dark|light` to the Notion URL when they are uploading it to Papermark. 
From there we are extracting it and passing it into the `NotionPage` component.

The actual Papermark link does not change

**Comment by mfts** [comment]
@DeepaPrasanna please have a look at my last comment

**Comment by DeepaPrasanna** [comment]
I am really sorry for the delay. I will update within few hours.

**Comment by mfts** [comment]
> I am really sorry for the delay. I will update within few hours.

No rush. I know you are also busy with other things. But great to keep this PR moving along.

**Comment by DeepaPrasanna** [comment]
> > I am really sorry for the delay. I will update within few hours.
> 
> No rush. I know you are also busy with other things. But great to keep this PR moving along.

Thank you for your patience :) I have taken into account your reviews and updated the code.

Pls also refer to the screen recording showing the changes
https://www.loom.com/share/74ed5f801a8f476fa182eb0468ff1557?sid=3de9bb42-8b69-4fa0-940e-f1ae5dd9f6a4

**Comment by DeepaPrasanna** [comment]
Hello @mfts wdyt about this?

**Review by mfts — APPROVED** [review]
Great job! Looks amazing and exactly how I imagined it. 

I made minor adjustments, such as adding it to `notionData` instead of `document` and also adding it to custom domain routes

**Comment by mfts** [comment]
Another cool idea would be to just make a button on the Notion document, that toggles dark/light mode and when toggled it changes the Notion url by appending / removing the `?mode=dark` url query param. 

Perhaps a task for a new PR before ossgg ends?

**Comment by DeepaPrasanna** [comment]
> @DeepaPrasanna Another cool idea would be to just make a button on the Notion document, that toggles dark/light mode and when toggled it changes the Notion url by appending / removing the `?mode=dark` url query param.
> 
> Perhaps a task for a new PR before ossgg ends?

It seems a cool one ! Am I correct in assuming that you are here referring to the document shown when hitting the papermark link?

**Pull request merged**
