### PR TITLE
feat: multiple document version

### LINKED ISSUE #70: Multiple document versions
It happens that you send a document with an error on page 3. The link is already on its way to the recipient. Don't you wish to correct that mistake without letting your recipient know. 

That's where document versions come in. Change the document without changing the link.

### PR DESCRIPTION
**Pull request by JoyBoy-369**
closes #70 

P.S. I wasn't certain if we wanted to capture document update events, so I refrained from adding it. Please let me know if this is something we are interested in tracking and, if so, I can incorporate the necessary changes.

### CODE REVIEW

**Comment by mfts** [comment]
Thank you so much for your effort. I have a PR in the works already that creates the UI for document versions and adjusts the tinybird ingestion pipeline: #108 

Do you want to take a look at my PR and see if some of your suggestions can be implemented there?

**Comment by JoyBoy-369** [comment]
I apologize for not reaching out to you before submitting my PR. I was unaware that there was already an existing PR in progress.

I took a look at your PR and looks great. It appears that my PR addresses only a subset of features. I did add a couple minor UI improvements related to keys and DOM nesting that you might want to consider.

**Comment by mfts** [comment]
Thanks @JoyBoy-369, I recently merged the versions UI and teams functionality into `main`. Please have a look and update your PR from main. Happy to take a look at your updates.

**Comment by mfts** [comment]
closing this as duplicate

**Pull request closed without merging**
