### PR TITLE
fix: inconsistent theme in 404 screen

### LINKED ISSUE #708: [🕹️] Light-Dark Mode Audit: 404 Screen
### What side quest or challenge are you solving?

Light-Dark Mode Audit
https://github.com/mfts/papermark/issues/631

### Points

50 to 300

### Description

The page not found text is not visible clearly in light mode
https://app.papermark.io/not-found

### Provide proof that you've completed the task

image

### PR DESCRIPTION
**Pull request by JeevaRamanathan**
Fixes #708 
image

### CODE REVIEW

**Comment by JeevaRamanathan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JeevaRamanathan** [comment]
recheck

**Review by mfts — APPROVED** [review]
Wow thanks! Finally. This was so annoying and we never got around to fixing it

**Pull request merged**
