### PR TITLE
feat: make agreement name customizable

### LINKED ISSUE #651: [🕹️] Make an agreement's display name customizable
### What side quest or challenge are you solving?

We have Agreements, which can be NDAs or Privacy Policies or any other kind of document that you'd like to have your viewer see before checking a document. 

Currently, we hardcode the display name to "Non-Disclosure Agreement". 

CleanShot 2024-10-04 at 14 46 42@2x

However, it would be great if we could customize the display name.

### Points

750 Points

### Description

Additional information: 

Here's the agreement configuration sheet, perhaps we can reuse the `name` field for the Display name or create a new table field for display name.
CleanShot 2024-10-04 at 14 46 17@2x

### Provide proof that you've completed the task

Open a PR with description of what you have done.

### PR DESCRIPTION
**Pull request by DeepaPrasanna**
fixes #651 

I have utilised the name field of the agreement to show instead of NDA or privacy policy which were hardcoded. I have tested locally when the linkType was DATAROOM.
image

but for linkType as DOCUMENT, I am unable to do so as I am encountering an error on viewing an uploaded document 
image

this error is not on production, I am still trying to figure what might have caused this.

### CODE REVIEW

**Comment by DeepaPrasanna** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by DeepaPrasanna** [comment]
Hey @TechWitkunal you have mentioned /assign on a pr. This is not an issue

**Comment by Meetpidev** [comment]
> I have read the CLA Document and I hereby sign the CLA

hey there.. how to sign CLA ?

**Comment by DeepaPrasanna** [comment]
Hello @mfts , it seems someone assigned my PR. I have already worked on this and was waiting for your reviews.

**Comment by mfts** [comment]
@DeepaPrasanna you are definitely first. I will close the original issue and award you here directly. 

I do have one change request: 
- could you please change the label on the "form" where we enter the name and add the NDA to "Display Name"

**Review by mfts — CHANGES_REQUESTED** [review]
could you please change the label on the "form" where we enter the name and add the NDA to "Display Name"

**Comment by DeepaPrasanna** [comment]
How is this?
Before: 
Screenshot 2024-10-11 202556
After:
Screenshot 2024-10-11 202809

Would you like me to change the htmlfor attribute value from name to display-name? I kept "name" for now.

**Review by mfts — APPROVED** [review]
Thanks for the quick fix :)

**Pull request merged**
