### PR TITLE
Fix/made the dataroom route protected in case user hasn't opted for any trial or plan

### PR DESCRIPTION
**Pull request by nidhish-srivastava**
Fixes issue #587 
 Ensuring that if user hasnt opted for any plan that is he is having free plan and no trial as well then no access to this dataroom route.
If user has lets say business plan but no trial at the moment,he can visit this dataroom page,he shudnt be redirected

### CODE REVIEW

**Review by mfts — APPROVED** [review]

**Comment by mfts** [comment]
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mfts/papermark/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

@nidhish-srivastava looks great! finally step before I can merge it in: signing the CLA

**Comment by nidhish-srivastava** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nidhish-srivastava** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfts** [comment]
@nidhish-srivastava are you taking part in oss.gg ? I'd love to assign you 150 Points for it :)

**Review by mfts — APPROVED** [review]

**Comment by nidhish-srivastava** [comment]
Yes i am taking part. It would be so nice of you giving me the points

**Pull request merged**
