### PR TITLE
[Feat] Added Pricing Page 

### LINKED ISSUE #627: [🕹️] Build Pricing Calculator
### What side quest or challenge are you solving?

Many Papermark users, sharing whole data room using one link. The data room market is complicated and pricing structures also. 

To attract more website visitors and make they life easier we would to have this price calculator on our landing page papermark.io

Here is an example: https://firmroom.com/calculator

Points: 750

Provide proof that you've completed the task

You'll get access to the repo of papermark to open your PR 🤓

### PR DESCRIPTION
**Pull request by Hitarthsheth07**
FIX #627 

_**NOTE: DO NOT PUSH THIS TO THE CODEBASE!**_

The file pages/pricing.tsx is just a simple implementation of how the pricing page should work and it is NOT supposed to pushed into the codebase. 
Use it as a reference point to create a pricing page. 

image

Desktop - 4

Check the figma file below for more details:

Figma Link:
[https://www.figma.com/design/XSJTbBuormBLtVjFd8fhhd/Untitled?node-id=0-1&t=P7SmrYzw9fmmyL7R-1](url)

### CODE REVIEW

**Comment by Hitarthsheth07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hitarthsheth07** [comment]
recheck

**Comment by Hitarthsheth07** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Hitarthsheth07** [comment]
recheck

**Comment by adityadeshlahre** [comment]
I would like to create the page @Hitarthsheth07 if you allow me ! :slightly_smiling_face: Thank You

**Comment by mfts** [comment]
@Hitarthsheth07 Thanks for the contribution. 

@adityadeshlahre That's ok. It s @Hitarthsheth07's contribution and we are adding it to the landing page repo.

**Comment by Hitarthsheth07** [comment]
> @Hitarthsheth07 Thanks for the contribution.
> 
> @adityadeshlahre That's ok. It s @Hitarthsheth07's contribution and we are adding it to the landing page repo.

Thanks @mfts

**Comment by Hitarthsheth07** [comment]
Heyy @mfts what's the status on this PR? Thanks.

**Comment by mfts** [comment]
@Hitarthsheth07 checking it today. thanks for your patience

**Comment by Hitarthsheth07** [comment]
> @Hitarthsheth07 checking it today. thanks for your patience

No problem, let me know if you need something from me.

**Comment by Hitarthsheth07** [comment]
@shnai0 The design is added. Please review it!

**Comment by Hitarthsheth07** [comment]
@shnai0 @mfts any updates?

**Comment by mfts** [comment]
/award 750

Thanks so much for your work! Looks pretty good.  @Hitarthsheth07  We will merge it on marketing page and as soon as we launch, tag you also.

**Pull request closed without merging**
