### PR TITLE
feat: watermark documents

### LINKED ISSUE #267: [feat] add watermarking to documents
- Add watermarks to links that includes the email and the datetime of the visitor. 
- Placement of the watermark should bottom right (in the future we can make it movable)

### PR DESCRIPTION
**Pull request by ashrafchowdury**
## Description
Implemented a feature watermark documents. Users can toggle the watermark on or off and move it around the document as needed. 
The watermark is placed at the bottom right of the document and can be moveable, showing the viewer's email and viewing time.

## Feature
+ Watermark documents.
+ Watermark is moveable within the document.

## Preview

https://github.com/mfts/papermark/assets/87828904/21f46375-d550-4900-9c71-43692d7343ed

## Issue

Closes #267

### CODE REVIEW

**Comment by mfts** [comment]
I like this but I think the watermark should not be movable. instead it should be permanently attached to the image in a fixed location. 

Not sure how to best make this happen quite yet but maybe you find a way :)

**Comment by ashrafchowdury** [comment]
Currently, We are unable to download the watermark along with the document. But I will keep an eye on it to make it more useable

**Comment by ashrafchowdury** [comment]
Hey @mfts, can you confirm if the pro version includes the watermark feature? What will be the default behaviour (open or close) if it's not included in the pro version? That way, I can make changes accordingly.

**Comment by mfts** [comment]
@ashrafchowdury this would most definitely be a pro feature. 

it would be awesome if we could manipulate the image before it hits the client. so far I only know of a solution that involves S3 lambda.

**Comment by ashrafchowdury** [comment]
> @ashrafchowdury this would most definitely be a pro feature.
> 
> it would be awesome if we could manipulate the image before it hits the client. so far I only know of a solution that involves S3 lambda.

If we manipulate the image most probably the watermark will fall into the empty space of the image.

**Comment by mfts** [comment]
Thanks for the initial project @ashrafchowdury. 

We just shipped watermarking here #576. You might find the approach slightly differently.

**Pull request closed without merging**
