### PR TITLE
fixes #938 adds scrollbar to add folder modal 

### LINKED ISSUE #938: [🕹️] Destination Folders become unreachable in "Move Folder" Modal when there are a lot of folders
### What side quest or challenge are you solving?

The issue is that when you try to move file(s) to a destination folder that is deeply nested, then the modal keeps expanding until it reaches the end of the screen, and it's not possible to move anymore. 

Possible Solution: make the modal scrollable with a max-height so that it can expand infinitely and still able to reach the destination folder and able to move the document 

CleanShot 2024-10-14 at 15 35 06@2x
CleanShot 2024-10-14 at 15 37 12@2x
 

### Points

300 Points

### Provide proof that you've completed the task

Open a PR with the working code and a detailed explanation of what you did, the use cases you tested and if possible, a video showing the solution.

### PR DESCRIPTION
**Pull request by sateshcharan**
resolves #938 
made the folders scrollable and restricted max height of modal
tested functionality, have attached working video & screenshot for reference

2024-10-16T20_14_30

https://github.com/user-attachments/assets/e2f94159-8581-4b85-b991-1e67ed5ad04f

### CODE REVIEW

**Comment by sateshcharan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sateshcharan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sateshcharan** [comment]
recheck

**Review by mfts — APPROVED** [review]
Amazing Thanks!

**Pull request merged**
