### PR TITLE
599-Add custome favicon icon in document link

### PR DESCRIPTION
**Pull request by AshishViradiya153**
### **PR CONTAINS**
A new user-friendly UI is implemented for adding a favicon icon.
Users can upload an image with the allowed file types (.png, .jpg, .jpeg, .ico) with a maximum size of 1MB.
File validation ensures the proper size and file type are uploaded.
The uploaded favicon will be displayed in the browser's tab as the link icon.
Fixed 500 Favicon error.

### CODE REVIEW

**Comment by AshishViradiya153** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfts** [comment]
Thanks @AshishViradiya153 will take a look today :)

**Comment by mfts** [comment]
@AshishViradiya153 are you taking part in oss.gg?

**Comment by AshishViradiya153** [comment]
Hasto (Yes)

**Review by mfts — COMMENTED** [review]
Looks great! 

Two things that would make it perfect: 
- merge in the current `main` branch so everything is up to date and no merge conflicts
- merge the two prisma migrations into one

**Comment by AshishViradiya153** [comment]
@mfts, I've merged the current main branch and combined the two Prisma migrations into one as requested. Everything is now up to date, and I've pushed the changes. Let me know if anything else is needed!

**Comment by AshishViradiya153** [comment]
Thanks for review @mfts.

**Review by mfts — APPROVED** [review]

**Pull request merged**
