### PR TITLE
fix: Keep state in dataroom view between document and dataroom view #783

### PR DESCRIPTION
**Pull request by Nithin-532**
Bug: The folderId state is getting resetted everytime when we changing the view.

Fix: I lifted the state of folderId in DataroomViewer component to DataroomView component.

[Screencast from 13-10-24 11_40_10 PM IST.webm](https://github.com/user-attachments/assets/7531f705-ca8e-4e4e-8766-bd6d6f2e3ccb)

### CODE REVIEW

**Comment by Nithin-532** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Nithin-532** [comment]
recheck

**Comment by mfts** [comment]
@Nithin-532 great job! it's such a simple change. 

One small request and probably that might take some fiddling around but even tho the folder state is preserved, for some reason the folder tree doesn't expand to the current folder automatically 

Could you test this with a deeply-nested file (i.e. 2 or more folders deep) and see if you can fix the issue :)

https://github.com/user-attachments/assets/4ca4f448-486e-46e3-864e-e8888d76b51a

**Comment by Nithin-532** [comment]
@mfts sure

**Comment by Nithin-532** [comment]
@mfts I somewhat solved the problem. Here is the video.

[Screencast from 14-10-24 05:57:38 PM IST.webm](https://github.com/user-attachments/assets/33c6ad0f-29af-4bc7-8662-e0c79c055194)

But I think this is not an optimal approach.
I nested through all the folders and children of those folders to find the path of the folderId that has been selected.

**Comment by mfts** [comment]
> But I think this is not an optimal approach.
> I nested through all the folders and children of those folders to find the path of the folderId that has been selected.

@Nithin-532 I see. let me know if you want me to review some part of the code

**Pull request closed without merging**
