### PR TITLE
A brief description for dataroom

### PR DESCRIPTION
**Pull request by AshishViradiya153**
fixes https://github.com/mfts/papermark/issues/684

Its contain two fixes...

1 Dataroom with description
2 Delete group shows "Not Same Text" even have a same group name text (fixed).

374804297-c17666dc-8d05-4626-bb4e-d8e4421533b7
374804398-c0a01bfb-7070-4d0a-9dc1-89843c889377
374804481-5966093d-8e72-4ced-9fc9-041ec7d25d46
375985530-3bee3ad9-5011-4d16-a48f-d1c2a5971261
375985558-e05f5090-9bef-47a6-9e32-e9405bddca0c

### CODE REVIEW

**Comment by AshishViradiya153** [comment]
@mfts could you check please.

**Comment by mfts** [comment]
@AshishViradiya153 I don't want to add a description to the dataroom just yet. Could you only add one fix per PR please?

**Comment by AshishViradiya153** [comment]
Sorry @mfts, I will create a separate PR next time for each change

**Comment by mfts** [comment]
@AshishViradiya153 do you want to modify this PR or close it altogether?

**Comment by AshishViradiya153** [comment]
@mfts, the second issue is fixed and in production. We can close this PR if we don’t want to add the dataroom description part for now.

**Pull request closed without merging**
