### PR TITLE
chore:add missing  PostgreSQL link

### PR DESCRIPTION
**Pull request by vamsi4845**
This PR updates the missing PostgreSQL link

### CODE REVIEW

**Comment by vamsi4845** [comment]
> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mfts/papermark/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request. Posted by the **CLA Assistant Lite bot**.

I have read the CLA Document and I hereby sign the CLA

**Comment by mfts** [comment]
recheck

**Comment by vamsi4845** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by mfts — APPROVED** [review]

**Comment by vamsi4845** [comment]
@mfts I am planning to contribute to this page: https://www.papermark.io/home. However, I don't find anything related to this page in the current repo. Is it a separate repo?

**Comment by mfts** [comment]
@vamsi4845 yes the marketing page is a different private repo. What type of change would you like to make?

**Pull request merged**
