### PR TITLE
fix: add proper spacing to add-document-button

### LINKED ISSUE #752: [🕹️] Inconsistent spacing and irresponsive button content
### What side quest or challenge are you solving?

Alignment improvement

### Points

150 ?

### Description

Steps to Reproduce:

Navigate to the https://app.papermark.io/documents
Observe the spacing around elements and button

Expected Behavior:
Spacing should be consistent across all elements in line.

### Provide proof that you've completed the task

before
Screenshot 2024-10-11 161833

after
Screenshot 2024-10-11 170423

### PR DESCRIPTION
**Pull request by souvikjs01**
fixes #752 
 This PR addresses the inconsistent spacing on the https://app.papermark.io/documents on mobile view. Adjustments have been made to ensure a more uniform and visually appealing layout.

Screenshot 2024-10-11 161833

Screenshot 2024-10-11 170423

### CODE REVIEW

**Review by mfts — CHANGES_REQUESTED** [review]
@souvikjs01 what would be really good is, if the button text would not wrap but instead fit so that's only one line instead of two. 

could you make that happen without changing the text content?

**Comment by souvikjs01** [comment]
> @souvikjs01 what would be really good is, if the button text would not wrap but instead fit so that's only one line instead of two.
> 
> could you make that happen without changing the text content?

Sure i'm working on it.

**Review by mfts — APPROVED** [review]
Looks great!

**Comment by mfts** [comment]
@souvikjs01 please sign the CLA as indicated above 

> Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mfts/papermark/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
>
> I have read the CLA Document and I hereby sign the CLA

**Comment by souvikjs01** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
