### PR TITLE
Enhancement#133 Updated the UI of the landing page 

### PR DESCRIPTION
**Pull request by professssor**
updated UI for #133

image

### CODE REVIEW

**Comment by professssor** [comment]
Can any moderator have a look at it ??

**Review by mfts — APPROVED** [review]
Looks really good! Thank you @professssor

**Review by mfts — CHANGES_REQUESTED** [review]
Can you run `npm run lint` and, there's an apostrophe error



```
./components/web/section3.tsx
--
7:15  Error: `'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.  react/no-unescaped-entities
```

**Comment by professssor** [comment]
### updated the section3 typo




**log for npm run lint**

$ npm run lint

> papermark@0.1.0 lint
> next lint


./app/(static)/open-source-investors/ClientPage.tsx
77:6  Warning: React Hook useMemo has a missing dependency: 'fuse'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/alternatives/brieflink.tsx
319:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
369:21  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/alternatives/docsend.tsx
318:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
368:21  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/alternatives/google-drive.tsx
321:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
371:21  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/alternatives/pandadoc.tsx
320:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
370:21  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/alternatives/pitch.tsx
318:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
368:21  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./pages/api/mupdf/convert-page.ts
12:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

./pages/api/mupdf/get-pages.ts
6:1  Warning: Assign arrow function to a variable before exporting as module default  import/no-anonymous-default-export

./pages/blog/product-hunt-launch.tsx
56:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
89:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
100:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
164:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
169:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
196:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
209:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
237:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
249:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
298:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
442:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
446:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element
459:11  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/billing/upgrade-plan-modal.tsx
31:6  Warning: React Hook useMemo has an unnecessary dependency: 'plan'. Either exclude it or remove the dependency array.  react-hooks/exhaustive-deps

./components/PagesViewer.tsx
27:6  Warning: React Hook useEffect has a missing dependency: 'trackPageView'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
42:6  Warning: React Hook useEffect has a missing dependency: 'trackPageView'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/PDFViewer.tsx
31:6  Warning: React Hook useEffect has a missing dependency: 'trackPageView'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
37:6  Warning: React Hook useEffect has a missing dependency: 'updateNumPages'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
60:6  Warning: React Hook useEffect has a missing dependency: 'trackPageView'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/view/access-form/index.tsx
42:6  Warning: React Hook useEffect has a missing dependency: 'setData'. Either include it or remove the dependency array. If 'setData' changes too often, find the parent component that defines it and wrap that definition in useCallback.  react-hooks/exhaustive-deps

./components/view/document-view.tsx
86:6  Warning: React Hook useEffect has a missing dependency: 'handleSubmission'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/web/header.tsx
 `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/web/section2.tsx
34:13  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

./components/web/testimonials.tsx
97:19  Warning: Using `` could result in slower LCP and higher bandwidth. Consider using `<Image />` from `next/image` to automatically optimize images. This may incur additional usage or cost from your provider. See: https://nextjs.org/docs/messages/no-img-element  @next/next/no-img-element

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rulinfo  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules

**Comment by professssor** [comment]
now, are the errors sorted ??

**Pull request closed without merging**
