### PR TITLE
Sortable document items for data rooms

### PR DESCRIPTION
**Pull request by Ashmash100**
### Description

Resolved issue : [475](https://github.com/mfts/papermark/issues/475)

### Demo

https://github.com/user-attachments/assets/3f16eea0-601f-49ef-aa11-a6cf3651fe8b

### CODE REVIEW

**Comment by mfts** [comment]
Hi @Ashmash100 that's a great starting point. 

A couple of points:

- folders **and** documents should be sortable together (i.e. doc1 can be on position 1, folder1 on position 2)
- we need a new database field on the `DataroomDocument` and `DataroomFolder` to manage the position
- add an api function that persists the position of the dragged item in the database

**Comment by mfts** [comment]
@Ashmash100 I implemented the dataroom sorting in #558 

Would love your help on other issues :)

**Comment by Ashmash100** [comment]
> @Ashmash100 I implemented the dataroom sorting in #558
> 
> Would love your help on other issues :)

@mfts That’s amazing! I apologize for not being able to complete the PR as I got a bit occupied. However, I wanted to say that I absolutely loved working with the codebase.

I was wondering if you might have any openings for a full-time frontend role. I would be thrilled to join the team and contribute more permanently.

**Comment by mfts** [comment]
@Ashmash100 no need to apologize. 

> I was wondering if you might have any openings for a full-time frontend role.
Not at this moment, but I'm happy to keep you up to date.

**Pull request closed without merging**
