### PR TITLE
gitpod setup completed

### PR DESCRIPTION
**Pull request by adilkadivala**
Now it is easy to contribute using gitpod, 

create account on gitpod,  and select forked repo,  then open on any Ide.

### CODE REVIEW

**Comment by mfts** [comment]
@adilkadivala Wow that's incredible. 

Does it come with a postgres database on gitpod?

**Comment by adilkadivala** [comment]
Hey @mfts  

it will just run command " npm run dev:prisma",

**Comment by mfts** [comment]
@adilkadivala Can you add a gitpod postgres as well 

https://www.gitpod.io/guides/gitpodify#postgresql

**Comment by adilkadivala** [comment]
oh it's nice,  okay Sure I'll do it, thanks

**Comment by adilkadivala** [comment]
Hey @mfts I have add a gitpod postgres,  so I'm rising a new PR..

**Pull request closed without merging**
