### PR TITLE
Feat: papermark logo redirect to /document

### PR DESCRIPTION
**Pull request by tushar-agarwal7**
Fixes: #772 

This PR implements a feature where clicking on the Papermark logo now redirects the user to the /document.This change improves navigation by providing a direct link to the document section, enhancing user accessibility.

Changes:
    Updated the logo's link to point to /document.
    Ensured that the routing is correctly handled without breaking any other functionality.

### CODE REVIEW

**Comment by mfts** [comment]
@tushar-agarwal7 I appreciate the speed and effort. However, we have to play by the rules and the issue is currently assigned to another player, therefore I cannot merge or award you just yet

**Comment by tushar-agarwal7** [comment]
@mfts  I understand the issue is already assigned.Please feel free to review my PR. I worked on this PR because the assigner hasn't solved this issue

**Review by mfts — APPROVED** [review]

**Comment by mfts** [comment]
@tushar-agarwal7 please sign the CLA as indicated above

**Comment by tushar-agarwal7** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tushar-agarwal7** [comment]
@mfts  done sir!

**Pull request merged**
