### PR TITLE
write handlesumbmit function and check email is ok not refactor submit code

### PR DESCRIPTION
**Pull request by Mdmehedihasanrifat**
Here I refactored the code and wrote the handleSubmit function and fix this problem API Call Triggered Despite Empty Email Field During Authentication
Issue:#715
opensource
opensourcess
[screen-capture.webm](https://github.com/user-attachments/assets/bf76fc02-bced-44f2-b78a-89faad9f6b69)

### CODE REVIEW

**Comment by Mdmehedihasanrifat** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfts** [comment]
@Mdmehedihasanrifat could you please merge in the current main branch and resolve any conflicts :)

**Comment by Mdmehedihasanrifat** [comment]
@mfts  I resolve all  conflicts :)

**Review by Mdmehedihasanrifat — COMMENTED** [review]
this is working fine and its don't have any kind of impact on other branch

**Comment by mfts** [comment]
@Mdmehedihasanrifat you deleted all the work that was done before with last login used and so on. 

Please merge the current main branch and adapt your code around it.

**Comment by mfts** [comment]
Sorry but you are removing code from a previous contribution. Please pull the latest main branch and make sure you don't delete code that was previously merged

**Comment by mfts** [comment]
Sorry but this PR deletes code from the login page which is vital and after several back and forth's it's still not resolved.

**Pull request closed without merging**
