### PR TITLE
added the custom not found page

### LINKED ISSUE #637: To have a better not found page.

### PR DESCRIPTION
**Pull request by Pratham271**
resolves #637

### CODE REVIEW

**Comment by mfts** [comment]
@Pratham271 thanks for the contribution. would you mind signing the CLA as indicated above, please :)

**Comment by Pratham271** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by mfts — CHANGES_REQUESTED** [review]
The `app/not-found.tsx` only works in the app directory. However, almost all pages are in the `pages/` directory.

The router cannot find the not-found page from app router and instead is looking for the 404 page in pages directory

**Comment by Pratham271** [comment]
@mfts  but locally when I added 404 page it was not working properly. Can you explain me again please the changes that you suggested

**Comment by Pratham271** [comment]
@mfts I have made the requested changes and now it is working fine for pages in the pages directory

**Comment by mfts** [comment]
@Pratham271 it's still causing an error. 

CleanShot 2024-10-13 at 14 14 55@2x


Can you also share a screenshot of what this improved error page looks like?

**Comment by Pratham271** [comment]
@mfts  by mistake I removed a closing div just before the p tag let me make it right

**Comment by Aditya-PS-05** [comment]
@mfts 
Please merge this if everything is good.

**Comment by mfts** [comment]
@Pratham271 the search is currently not working. Also the buttons don't make sense, especially since an external visitor will see it and they may not have a papermark account so home, documents and settings are useless to them. 

I will award you for your effort but close this PR for now. 

/award 50

**Pull request closed without merging**
