### PR TITLE
[WIP] feat:pitch desks collection page

### LINKED ISSUE #628: [🕹️] Create page with collection of popular pitch decks
This page will be the collection of pitch decks from top companies who fundraised, like Airbnb and Etc. 

Each pitch deck should  have separate page with description, and be hosted on Papermark and have link leading to open it on Papermark. 

Example: https://slidebean.com/pitch-deck-template

Points: 750

### PR DESCRIPTION
**Pull request by adityadeshlahre**
- fixes #628

### DEMO
deck

### DARK
image

### CODE REVIEW

**Comment by shnai0** [comment]
@adityadeshlahre  I just implemented the page and it looks smooth! 

But I am missing the subpages. Linking the issue where I describe it.https://github.com/mfts/papermark/issues/628  It should be a slug page. 

Example like that https://slidebean.com/templates/uber-pitch-deck

1. Header (the link will lead to papermark, so we dont need images under header, only image on the right) 
2. Than block with text 

I will connect it to database later. Would you be able to add it?

**Comment by adityadeshlahre** [comment]
image
image

Hey @shnai0 rn what am trying to do it integrate it with the backend { I just copied the backend which implemented for documents all the function and stuff }

right now I have don't some change in prisma schema but I am not sure should I do the migrations or not for my created schema { in the latest commed you can see the prisma  schema related changes}

I will do the above mention changes soon :slightly_smiling_face: 

help me up with the change you want in my PR 

thank You

further implementation 

image

**Comment by adityadeshlahre** [comment]
### Preview Video

https://github.com/user-attachments/assets/5ae58ec9-3f76-4818-894c-67330b5c96dd

**Comment by mfts** [comment]
/award 1500

Thanks so much for great work! please share your Twitter and Linkedin handle than we can mention you as ssoon as implement it on our marketing pages.

**Pull request closed without merging**
