### PR TITLE
papermark logo submission oss.gg[side quest] #805

### PR DESCRIPTION
**Pull request by FelixFelicis99**
this pr is for submission of new logo for papermark 

* logo creation : https://github.com/mfts/papermark/issues/805

points : 150 Points for logo, 750 for the winner

### CODE REVIEW

**Comment by FelixFelicis99** [comment]
recheck

**Comment by FelixFelicis99** [comment]
recheck

**Comment by FelixFelicis99** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mfts** [comment]
already awarded in #805

**Pull request closed without merging**
