### PR TITLE
fix onboarding ui issue

### LINKED ISSUE #1300: [🕹️] on-boarding ui issue
### What side quest or challenge are you solving?

it's on four on-boarding page...
image

### Points

?

### Description

_No response_

### Provide proof that you've completed the task

Pr

### PR DESCRIPTION
**Pull request by AshishViradiya153**
fixes #1300

### CODE REVIEW

**Comment by Khaan25** [comment]
Personally, I'm not really a fan of adding max heights all over the code, there must be a better solution... 🤔

**Comment by AshishViradiya153** [comment]
Same here, Why do we need to be a big fan of anything in CSS? but sometimes practical solutions get the job done more efficiently! 😄

**Comment by Khaan25** [comment]
It's gonna create problems for others...

**Comment by AshishViradiya153** [comment]
It won’t! It’s totally separate, but I’ll double-check everything just to be sure!

**Comment by mfts** [comment]
I was currently fixing just saw that you made a PR for it. 

/award 150

**Pull request closed without merging**
