### PR TITLE
last used indicator on login page fixed

### PR DESCRIPTION
**Pull request by sahiladit**
Fixes:#841

#what does this pr do:
Now the indicator now only pops up when user click on any of the login mode and not when the user enters for the first time.

### CODE REVIEW

**Comment by mfts** [comment]
@sahiladit could you please share a video what you mean? if the user hasn't logged in ever then of course there's no "last used".

**Comment by sahiladit** [comment]
> @sahiladit could you please share a video what you mean? if the user hasn't logged in ever then of course there's no "last used". 
> 
>  

It fixes #841

**Review by mfts — APPROVED** [review]

**Comment by mfts** [comment]
ok sounds good. please sign the CLA

**Comment by sahiladit** [comment]
> ok sounds good. please sign the CLA

Can you give me the steps to sign it? It's my first time contributing to an org..

**Comment by mfts** [comment]
@sahiladit 

>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mfts/papermark/blob/main/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA

You can retrigger this bot by commenting recheck in this Pull Request. Posted by the CLA Assistant Lite bot.

**Comment by sahiladit** [comment]
recheck

**Comment by sahiladit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sahiladit** [comment]
recheck

**Comment by JeevaRamanathan** [comment]
Hi @sahiladit, It's great to hear on your first contribution, many more to go! One small thing...I tried with incorporating your but I seems like the similar behavior still on. The expected behaviour is until it get's navigated to the next screen / till successful login the indicator shouldn't show. And say lastlogin is indicating on `Google` and if the user click `LinkedIn` it should set to linkedin only when the user comes back again to login screen. Otherwise maybe you can try sharing a video if it works accordingly like mentioned.
**Expected:**

https://github.com/user-attachments/assets/91c91ca2-414b-4df8-b83a-77b8ca305915



https://lex.page/auth
https://app.formbricks.com/auth/login

And a sample implementations can be find here
https://github.com/formbricks/formbricks/pull/3376

**Comment by sahiladit** [comment]
> Hi @sahiladit, It's great to hear on your first contribution, many more to go! One small thing...I tried with incorporating your but I seems like the similar behavior still on. The expected behaviour is until it get's navigated to the next screen / till successful login the indicator shouldn't show. And say lastlogin is indicating on `Google` and if the user click `LinkedIn` it should set to linkedin only when the user comes back again to login screen. Otherwise maybe you can try sharing a video if it works accordingly like mentioned. **Expected:**
> 
>  13.10.2024_12.02.42_REC.mp4 
> https://lex.page/auth https://app.formbricks.com/auth/login
> 
> And a sample implementations can be find here [formbricks/formbricks#3376](https://github.com/formbricks/formbricks/pull/3376)

I think i have resolved this ,try to run my code ,it's not merged yet,and if you still find it let me know.

**Comment by JeevaRamanathan** [comment]
> I tried with incorporating your
*changes

Hi @sahiladit, I’m aware the code hasn’t been merged yet. Before posting my previous comment, I incorporated your changes into the code (tried with your code), but the issue still remains. Would you mind checking it :-)

**Comment by sahiladit** [comment]
> > I tried with incorporating your
> > *changes
> 
> Hi @sahiladit, I’m aware the code hasn’t been merged yet. Before posting my previous comment, I incorporated your changes into the code (tried with your code), but the issue still remains. Would you mind checking it :-)

Okay,thanks for the check, i'll try to resolve it.

**Comment by mfts** [comment]
@sahiladit any update on the last changes?

**Comment by sahiladit** [comment]
> @sahiladit any update on the last changes?

Making some changes, will open a pr today.

**Comment by mfts** [comment]
@sahiladit just add to this PR :)

**Comment by sahiladit** [comment]
how can i change the code in existing pr?

**Comment by sahiladit** [comment]
i have made the changes,should i recheck it here?

**Review by mfts — APPROVED** [review]

**Review by mfts — CHANGES_REQUESTED** [review]
@sahiladit there's a build error. 

```
TypeError: Cannot destructure property 'data' of '(0 , N.useSession)(...)' as it is undefined.
    at Z (/vercel/path0/.next/server/app/(auth)/login/page.js:1:9627)
    at nj (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nI (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680) {
  digest: '600978353'
}
Error occurred prerendering page "/login". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot destructure property 'data' of '(0 , N.useSession)(...)' as it is undefined.
    at Z (/vercel/path0/.next/server/app/(auth)/login/page.js:1:9627)
    at nj (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nI (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
    at nM (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61546)
    at nN (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
    at nB (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
    at nD (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
   Generating static pages (8/35) 
   Generating static pages (17/35) 
   Generating static pages (26/35) 
```


please resolvre that and try to `npm run build` it yourself locally first

**Comment by mfts** [comment]
Thanks for your effort. I didn't hear back from you, so I implemented it myself here https://github.com/mfts/papermark/pull/1296

Awarding you for the effort nonetheless
/award 25

**Pull request closed without merging**
