### PR TITLE
Cloud setup using gitpod is ready to go   #816

### PR DESCRIPTION
**Pull request by adilkadivala**
Now it's not necessary to setup project on local environment, we can contribute using cloud setup,

### CODE REVIEW

**Comment by adilkadivala** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by adilkadivala** [comment]
hey @mfts Is my PR have any issue for Merging it ?

**Comment by mfts** [comment]
@adilkadivala your PR is still in draft mode. could you please record a brief video how the setup looks like with gitpod?

**Pull request closed without merging**
